name: Deploy production image

# TODO add workflow run
# To use workflow_run the file needs to be on master -> add in new pr
on:
  push:
    branches: ["*"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Docker tags
        run: |
          echo "tag=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Log into GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./
          file: .docker/dockerfile.api.k8s
          # tags: ghcr.io/sagensagen/tdctl-frontend:${{ env.tag }}
          tags: ghcr.io/sagensagen/tdctl-api:latest
